eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888

spring:
  application:
#    name: spring-cloud-demo-config-server
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ckdxc/spring-cloud-config.git     # 配置git仓库的地址
          search-paths: respo                           # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                             # git仓库的账号（私有库必填）
          password:                                             # git仓库的密码（私有库必填）
      label: master                                        #配置git仓库的分支