spring:
  application:
    name: spring-cloud-demo-config
  cloud:
    config:
      # spring.cloud.config.label：配置仓库的分支
#      label: master
      server:
        git:
          # 如果使用 GitLab 作为仓库的话，git.uri 需要在结尾加上 .git，GitHub 则不用
          # spring.cloud.config.server.git.uri：配置 Git 仓库地址（GitHub、GitLab、码云 ...）
          uri: https://github.com/ckdxc/spring-cloud-config.git
          # pring.cloud.config.server.git.search-paths：配置仓库路径（存放配置文件的目录）
          search-paths: respo
          # 如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
          # spring.cloud.config.server.git.username：访问 Git 仓库的账号
#          skipSslValidation: true #跳过校验
          username:
          # spring.cloud.config.server.git.password：访问 Git 仓库的密码
          password:

# 默认端口: 8888此处修改端口无效,需要创建bootstrap.yml配置server.port修改此项目启动端口(bootstrap.yml优先加载)
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

